export const CAMPUS_BUILDINGS = [
  "Addie Klotz Student Health Center",
  "Art and Design Center",
  "Autodesk Technology Engagement Center (ATEC)",
  "Bayramian Hall",
  "Bookstein Hall",
  "Chaparral Hall",
  "Citrus Hall",
  "Cypress Hall",
  "Education Building",
  "Eucalyptus Hall",
  "Extended University Commons",
  "Goodman Hall",
  "Jacaranda Hall",
  "Jerome Richfield Hall",
  "Live Oak Hall",
  "Manzanita Hall",
  "Matador Bookstore",
  "Nordhoff Hall",
  "Orange Grove",
  "Police Services",
  "Redwood Hall",
  "Sequoia Hall",
  "Sierra Center",
  "Sierra Hall",
  "Student Recreation Center",
  "The Soraya",
  "University Library",
  "University Student Union",
  "University Park Apartments",
  "Other campus location",
];